Arrays

1D Array

In [1]:
import numpy as np

In [3]:
a= np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
b= np.zeros(3)

print(b)

[0. 0. 0.]


In [6]:
c=np.ones(4)
print(c)

[1. 1. 1. 1.]


In [7]:
d= np.empty(3)
print(d)

[0. 0. 0.]


In [8]:
e= np.arange(5)
print(a)

[1 2 3 4 5]


In [9]:
f= np.arange(2,10)
print(f)

[2 3 4 5 6 7 8 9]


In [10]:
g= np.arange(2,15,2)
print(g)

[ 2  4  6  8 10 12 14]


In [12]:
h= np.linspace(1,15,num=3)

print(h)

[ 1.  8. 15.]


In [21]:
i=np.ones(5, dtype=np.int8)
print(i)

[1 1 1 1 1]
