2d arrays

In [1]:
import numpy as np

In [4]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
b=np.ones((4,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
c= np.empty((2,5))
print(c)

[[nan  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
